"""Add multi-tenancy support

Revision ID: 7803fdbe886c
Revises: 0bb270530b50
Create Date: 2025-10-17 17:30:25.084804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7803fdbe886c'
down_revision = '0bb270530b50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('asset', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'asset', 'tenant', ['tenant_id'], ['id'])
    op.add_column('business_startup_activity', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'business_startup_activity', 'tenant', ['tenant_id'], ['id'])
    op.add_column('expense', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'expense', 'tenant', ['tenant_id'], ['id'])
    op.add_column('financial_params', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'financial_params', 'tenant', ['tenant_id'], ['id'])
    op.add_column('liability', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'liability', 'tenant', ['tenant_id'], ['id'])
    op.add_column('product', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'product', 'tenant', ['tenant_id'], ['id'])
    op.add_column('user', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'tenant', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'tenant_id')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'tenant_id')
    op.drop_constraint(None, 'liability', type_='foreignkey')
    op.drop_column('liability', 'tenant_id')
    op.drop_constraint(None, 'financial_params', type_='foreignkey')
    op.drop_column('financial_params', 'tenant_id')
    op.drop_constraint(None, 'expense', type_='foreignkey')
    op.drop_column('expense', 'tenant_id')
    op.drop_constraint(None, 'business_startup_activity', type_='foreignkey')
    op.drop_column('business_startup_activity', 'tenant_id')
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.drop_column('asset', 'tenant_id')
    op.drop_table('tenant')
    # ### end Alembic commands ###
